### ISSUE TITLE
É possível utilizar este sistema em outra instituição?

### ISSUE THREAD

**Issue by frankthedead** [CosmeLorim/Sistema-de-Reservas-UNEMAT#1]
Preciso de algo específico pra rodá-lo?

**Comment by CosmeLorim** [comment]
Sim, é possível, os pré-requisitos são apenas Node.js 6.11.0 +, PostgreSQL 9.5 +, npm para instalar as dependências e o esquema do banco(ainda não disponibilizado no repositório).
Mas ainda não há meios de customizar visualmente o sistema, sendo assim é necessário modificar direto no código fonte.

**Comment by CosmeLorim** [comment]
Se você estiver procurando um sistema semelhante para fazer implementação talvez o Sistema de Reserva de Salas e Equipamentos (SiRe) do Instituto de Ciências Exatas e Aplicadas (ICEA) Campus João Monlevade da Universidade Federal de Ouro Preto (UFOP), disponível nesse [repositório](https://github.com/jpmoura/sire/tree/generico) possa te servir. 
Recentemente o dono do repositório criou uma _branch_ chamada _generico_ para que qualquer pessoa possa usar o sistema agora, não só pessoas vinculadas a UFOP. Dessa forma você pode instalar e testar o sistema sem nenhum problema.
Esse sistema está mais maduro que o meu, inclusive recomendaria utilizar o dele ao meu.

**Comment by frankthedead** [comment]
Já estou utilizando, obrigado pela dica.
